swagger:
  resourcePackage: net.zetlan.orderserve

server:
  type: simple
  applicationContextPath: /v1

database:
  driverClass: org.h2.Driver
  user: zola
  url: jdbc:h2:./order-serve
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: update
